### PR TITLE
Add CC BY 4.0 License to footer

### PR DESCRIPTION
**Pull request by ianhanssoniohk**

### CODE REVIEW

**Comment by KtorZ** [comment]
What do you think about adding a `LICENSE` file at the root with the legal code corresponding to CC-BY (https://creativecommons.org/licenses/by/4.0/legalcode.en) to make it easy to discover.

**Comment by olgahryniuk** [comment]
@ianhanssoniohk, please take a look at the comment above. I believe we can merge this PR after addressing that. Many thanks

**Comment by ianhanssoniohk** [comment]
@olgahryniuk @KtorZ The LICENSE file has now been added to the root.

**Comment by olgahryniuk** [comment]
Thanks so much, everyone! Merging now.

**Review by olgahryniuk — APPROVED** [review]

**Pull request merged**
