### PR TITLE
Ambiguous description of rewards distribution

### PR DESCRIPTION
**Pull request by psychomb**
The second part of the description regarding rewards distribution among pool owners sounds ambiguous ('are distributed').

### CODE REVIEW

**Comment by nahern** [comment]
this is described correctly as it stands.

**Comment by psychomb** [comment]
Thanks @nahern for following up this. 

"The rewards [...] are distributed by the protocol amongst the owner accounts."
That is precisely because the owners rewards end up in a single account that trust needs to exist between the unique operator and the - may be several - owners of a pool.

Unless my english betrays me here (non-native), this last part implies quite the contrary.

**Review by nahern — APPROVED** [review]
approved

**Comment by nahern** [comment]
removed ambiguity - thanks for your feedback

**Pull request merged**
