### PR TITLE
Add components already compatible with Cardano-Node v9.0/9.1

### PR DESCRIPTION
**Pull request by linconvidal**

### CODE REVIEW

**Comment by linconvidal** [comment]
Hi, can someone please review this PR? 
@olgahryniuk @NeilBurgess42 @fstoqnov-iohk

**Review by NeilBurgess42 — APPROVED** [review]
Checked all new links, could not see a reason for the preview build failure.

**Comment by NeilBurgess42** [comment]
The build fails after 3seconds, missing a parameter value.

**Comment by linconvidal** [comment]
@FerralBunny Same issue. It seems that the Vercel token is missing:

`Error: Input required and not supplied: vercel-token`

Could this be a permission-related issue? My pull requests have never been able to deploy to preview in this repository.

**Comment by linconvidal** [comment]
@FerralBunny Is there anything I can do to help resolve this?

**Pull request closed without merging**
