### PR TITLE
Link to Mithril docs

### PR DESCRIPTION
**Pull request by eyeinsky**

### CODE REVIEW

**Comment by olgahryniuk** [comment]
Thanks @eyeinsky for the PR. On Cardano Docs, both Hydra and Mithril work as external links. I am not sure we need to add them to the file.
cc @fstoqnov-iohk

**Comment by olgahryniuk** [comment]
Because the links work as external ones, I'll close this PR. Thanks!
image

**Comment by eyeinsky** [comment]
Sure, but page looks empty (like below).
Screenshot_2023-09-14_19-28-36

Maybe there is a way to have no empty pages for them at all?

**Comment by olgahryniuk** [comment]
Hm, I suppose the only way to get this view is by clicking 'Next' from the previous 'Sidechains Overview' page. You can't get this from the navigation menu...

Let's try adding those links then.

**Review by olgahryniuk — APPROVED** [review]

**Pull request merged**
